set(_CATKIN_CURRENT_PACKAGE "model_predictive_contouring_control")
set(model_predictive_contouring_control_VERSION "0.0.0")
set(model_predictive_contouring_control_MAINTAINER "syseng402 <syseng402@todo.todo>")
set(model_predictive_contouring_control_PACKAGE_FORMAT "2")
set(model_predictive_contouring_control_BUILD_DEPENDS "std_msgs" "roscpp" "utilities")
set(model_predictive_contouring_control_BUILD_EXPORT_DEPENDS "utilities")
set(model_predictive_contouring_control_BUILDTOOL_DEPENDS "catkin")
set(model_predictive_contouring_control_BUILDTOOL_EXPORT_DEPENDS )
set(model_predictive_contouring_control_EXEC_DEPENDS "std_msgs" "roscpp" "utilities")
set(model_predictive_contouring_control_RUN_DEPENDS "std_msgs" "roscpp" "utilities")
set(model_predictive_contouring_control_TEST_DEPENDS )
set(model_predictive_contouring_control_DOC_DEPENDS )
set(model_predictive_contouring_control_URL_WEBSITE "")
set(model_predictive_contouring_control_URL_BUGTRACKER "")
set(model_predictive_contouring_control_URL_REPOSITORY "")
set(model_predictive_contouring_control_DEPRECATED "")